version: '2'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - redis-dev
      - selenium-dev
    volumes:
      - ./app:/app
    env_file: .env.local

  redis-dev:
    image: redis:alpine
    volumes:
      - ./redis/data:/data

  selenium-dev:
    image: selenium/standalone-firefox
